version: '3'

services:
  licensingservice:
    image: chsubhasis/licensesvc:DEV1.0
    ports:
      - "8080:8080"
    environment:
       SPRING_PROFILES_ACTIVE: "dev"
       SPRING_CLOUD_CONFIG_URI: http://configserver:8071